### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by arekbulski** [commonsense/divisi2#8]
When `pip install conceptnet` failed due to it supporting only Python 3, I switched to 3. Now it seems both `divisi` and `divisi2` support only Python 2? 

How do I get divisi on 3?

**Comment by rspeer** [comment]
I'm going to guess you're following a pretty old tutorial. Divisi was obsoleted by Pandas and SciPy about 6 years ago.

ConceptNet-specific utilities for vector similarity can be found in `conceptnet5.vectors`, and some pre-baked semantic vectors that result from it are in [conceptnet-numberbatch](https://github.com/commonsense/conceptnet-numberbatch).

**Comment by arekbulski** [comment]
I need to install CN on Windows. Can you direct me?

**Comment by rspeer** [comment]
I see you're in Gitter also -- I'll respond there.

**Comment by arekbulski** [comment]
I am there.
