### ISSUE TITLE
Class "SparseMatrix" doesn't have method "edges_iter"

### ISSUE THREAD

**Issue by kagan94** [commonsense/divisi2#9]
Hello.
I tried to install the module on both, Windows and Ubuntu (Python 2.7.13) and got this error:
` File "..\divisi2\network.py", line 114, in sparse_triples
    first_edge = graph.edges_iter(data=True).next()
AttributeError: 'SparseMatrix' object has no attribute 'edges_iter'`

Could you look at it?
Thanks in advance!

**Comment by rspeer** [comment]
I should update the front page of this repository. Divisi2 isn't maintained anymore, because everything it did is done better by `scipy.sparse` for sparse matrices and `pandas` for labeled data.

**Comment by rspeer** [comment]
Oh, and the big thing that supersedes what divisi2 was for is the `conceptnet5.vectors` module of the [conceptnet5](https://github.com/commonsense/conceptnet5) repository, for building state-of-the-art word vectors.
